# Site settings
title: Moon
name: yuxr # your name
email: moonyuxr@gmail.com # your email address
description: >
    程序猿中 我不是弹吉他最好的那一个  火锅呢？
baseurl: "/moon" # the subpath of your site, e.g. /blog
url: "https://yuxr.github.io/moon/" # the base hostname & protocol for your site
twitter_username: # your Twitter username
github_username: moonyuxr
disqus_username: # your disqus username

google-analytics: # add it if you have one

skillstree: true # turn on or off the skills tree in about page

# Build settings
permalink: none
markdown: kramdown
